spring:
  application:
    name: Anti-Fake-DaybreakNews-Backend
  profiles:
    active: db

  datasource:
    url: jdbc:mysql://localhost:3307/daybreakdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  
  servlet:
    multipart:
      max-file-size: 10MB

supabase:
  storage:
    endpoint: ${SUPABASE_STORAGE_ENDPOINT:https://gdvmhaboyscqbpiwggrn.supabase.co/storage/v1/s3}
    endpoint_output: ${SUPABASE_STORAGE_ENDPOINT_OUTPUT:https://gdvmhaboyscqbpiwggrn.supabase.co/storage/v1/object/public}
    bucket: ${SUPABASE_BUCKET_NAME:images}
    region: ${SUPABASE_STORAGE_REGION:ap-southeast-1}
    accessKey: ${SUPABASE_ACCESS_KEY:}
    secretKey: ${SUPABASE_SECRET_KEY:}

application:
  security:
    jwt:
      secret-key: 9aGjT630/amFgq6Cr8nT0Nmv+fM+4tCQZQnFhAPztGTg5Uu/IzQuwA/42wfhUkV/5a/Jshyj+jJ+XAmtUqf+Aw==
      expiration: 86400000
      refresh-token:
        expiration: 604800000

server:
  port: 8080
