spring:
  application:
    name: Anti-Fake-DaybreakNews-Backend
  profiles:
    active: db

  datasource:
    url: jdbc:h2:mem:fakenewsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  
  h2:
    console:
      enabled: true 
  servlet:
    multipart:
      max-file-size: 10MB

supabase:
  url: https://gdvmhaboyscqbpiwggrn.supabase.co
  anon-key: ${SUPABASE_ANON_KEY}
  service-key: ${SUPABASE_SERVICE_KEY}
  bucket-name: ${SUPABASE_BUCKET_NAME:news-images}

server:
  port: 8080
