spring:
  application:
    name: Anti-Fake-DaybreakNews-Backend
  profiles:
    active: db

  datasource:
    url: jdbc:mysql://localhost:3307/daybreakdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  
  servlet:
    multipart:
      max-file-size: 10MB

supabase:
  url: https://gdvmhaboyscqbpiwggrn.supabase.co
  anon-key: ${SUPABASE_ANON_KEY}
  service-key: ${SUPABASE_SERVICE_KEY}
  bucket-name: ${SUPABASE_BUCKET_NAME:news-images}

application:
  security:
    jwt:
      secret-key: 9aGjT630/amFgq6Cr8nT0Nmv+fM+4tCQZQnFhAPztGTg5Uu/IzQuwA/42wfhUkV/5a/Jshyj+jJ+XAmtUqf+Aw==
      expiration: 86400000
      refresh-token:
        expiration: 604800000

server:
  port: 8080
