spring:
  datasource:
    url: jdbc:h2:mem:fakenewsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  
  h2:
    console:
      enabled: true

